### ISSUE TITLE
More topic should should be shown

### ISSUE THREAD

**Issue by RITESHMOHAPATRA** [NJACKWinterOfCode/WIKIPEDIA-READER#2]
It extracts the only first paragraph of query in wikipedia , we have to extract everything display it and read out it.

**Comment by aryadas98** [comment]
I have edited the code to display the full article. But now, the tts is not working. The tts works for short articles, but not for long ones. Should I still submit a pull request?


![device-2017-12-03-144828](https://user-images.githubusercontent.com/10235437/33523947-3716d1ae-d839-11e7-8e5e-f98192803ed8.png)

**Comment by aryadas98** [comment]
It is a problem with the tts engine. It won't speak anything more than 4000 chars. It's mentioned in the docs:
[TextToSpeech | Android Developers](https://developer.android.com/reference/android/speech/tts/TextToSpeech.html#speak(java.lang.CharSequence,%20int,%20android.os.Bundle,%20java.lang.String))

**Comment by aryadas98** [comment]
*UPDATE*: I fixed it by breaking up the article into chunks of 3000 characters and playing each chunk one after the other.
