### ISSUE TITLE
Add app icon

### ISSUE THREAD

**Issue by RITESHMOHAPATRA** [NJACKWinterOfCode/WIKIPEDIA-READER#2]
Add an app icon suitable for the app.

**Comment by rob729** [comment]
I would like to work on this issue

**Comment by RITESHMOHAPATRA** [comment]
ok

**Comment by rob729** [comment]
Since no difficulty level tag has been added to this issue so will it be the right time to start working on this issue ?

**Comment by RITESHMOHAPATRA** [comment]
You can start now

**Comment by rob729** [comment]
ok 
Thanks

**Comment by rob729** [comment]
[https://cdn0.tnwcdn.com/wp-content/blogs.dir/1/files/2010/05/wikipedia1.png](url)
Is this image good for app icon ?

**Comment by RITESHMOHAPATRA** [comment]
Not able to open it. Integrate the image in the code. Then I will review it when you PR it.

**Comment by rob729** [comment]
#4 I have send this pull request. Please review my PR.

**Comment by rob729** [comment]
@RITESHMOHAPATRA why have you reopened this issue?

**Comment by RITESHMOHAPATRA** [comment]
there was problem in content.xml. please commit your code again.

**Comment by rob729** [comment]
Ok

**Comment by rob729** [comment]
#5 This is PR for this issue.

**Comment by rob729** [comment]
@RITESHMOHAPATRA Is there anything else left to be done for this issue?
